on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Create Release and Publish to Marketplace
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install

      - name: Calculate version from package.json
        id: calculatePackageVersion
        run: |
          PACKAGE_VERSION=`cat package.json | jq ".version" -M | sed 's/\"//g'`
          echo "::set-output name=PackageVersion::$PACKAGE_VERSION"
          echo "package version = $PACKAGE_VERSION"
      
      - name: Package extension
        run: npm run vsce package

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          tag_name: v${{ steps.calculatePackageVersion.outputs.PackageVersion }}
          files: |
            FabricStudio-*.vsix
            CHANGELOG.md

      - name: Publish extension
        env:
          VSCE_PUBLISH_TOKEN: ${{ secrets.VSCE_PUBLISH_TOKEN }}
        run: npm run vsce --publish -p $VSCE_PUBLISH_TOKEN